package cli

import (
	"embed"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"io"
	"io/fs"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strconv"
	"strings"
	"text/template"
)

//go:embed templates/starter/* templates/starter/docs/* templates/starter/content/* templates/starter/agents/* templates/starter/public/* templates/starter/.agents/skills/docs-authoring/*
var starterTemplates embed.FS

// Run executes the fastr-docs CLI. Keeping the command runner as a small
// package makes it possible to test project generation without spawning the
// installed binary.
func Run(args []string, stdout, stderr io.Writer) error {
	if stdout == nil {
		stdout = io.Discard
	}
	if stderr == nil {
		stderr = io.Discard
	}
	if len(args) == 0 {
		printUsage(stdout)
		return nil
	}
	switch args[0] {
	case "help", "-h", "--help":
		printUsage(stdout)
		return nil
	case "version", "--version":
		_, _ = fmt.Fprintln(stdout, "fastr-docs dev")
		return nil
	case "init":
		return runInit(args[1:], stdout, stderr)
	case "check":
		return runCheck(args[1:], stdout)
	case "validate":
		return runCheck(args[1:], stdout)
	case "doctor":
		return runDoctor(args[1:], stdout, stderr)
	case "build":
		return runGo(args[1:], "build", []string{"./..."}, stdout, stderr)
	case "dev":
		return runGo(args[1:], "run", []string{"."}, stdout, stderr)
	case "export":
		return runExport(args[1:], stdout, stderr)
	default:
		return fmt.Errorf("unknown command %q (run `fastr-docs help`)", args[0])
	}
}

func runDoctor(args []string, stdout, stderr io.Writer) error {
	if err := runCheck(args, stdout); err != nil {
		return err
	}
	if err := runGo(args, "mod", []string{"tidy"}, stdout, stderr); err != nil {
		return err
	}
	return runGo(args, "test", []string{"./..."}, stdout, stderr)
}

func runInit(args []string, stdout, stderr io.Writer) error {
	flags := flag.NewFlagSet("init", flag.ContinueOnError)
	flags.SetOutput(stderr)
	name := flags.String("name", "", "site name shown in the generated docs")
	module := flags.String("module", "", "Go module path for the new project")
	force := flags.Bool("force", false, "overwrite files generated by fastr-docs")
	flagArgs, positionals, err := splitInitArgs(args)
	if err != nil {
		return err
	}
	if err := flags.Parse(flagArgs); err != nil {
		return err
	}
	target := "."
	if len(positionals) > 0 {
		target = positionals[0]
	}
	absTarget, err := filepath.Abs(target)
	if err != nil {
		return fmt.Errorf("resolve target: %w", err)
	}
	if *name == "" {
		*name = humanize(filepath.Base(absTarget))
	}
	if *module == "" {
		*module = filepath.ToSlash(filepath.Join("example.com", strings.ToLower(filepath.Base(absTarget))))
	}
	data := templateData{SiteName: strings.TrimSpace(*name), Module: strings.TrimSpace(*module)}
	if data.SiteName == "" || data.Module == "" {
		return errors.New("site name and module must not be empty")
	}
	if strings.ContainsAny(data.SiteName, "\r\n") {
		return errors.New("site name must not contain newlines")
	}
	if !validModulePath(data.Module) {
		return fmt.Errorf("invalid module path %q", data.Module)
	}
	data.LocalReplace = localFastrDocsReplace(absTarget)
	if err := writeStarter(absTarget, data, *force); err != nil {
		return err
	}
	_, _ = fmt.Fprintf(stdout, "created fastr-docs project in %s\n", absTarget)
	_, _ = fmt.Fprintln(stdout, "next: cd "+absTarget+" && fastr-docs check && go run .")
	return nil
}

func splitInitArgs(args []string) (flags, positionals []string, err error) {
	for i := 0; i < len(args); i++ {
		arg := args[i]
		switch arg {
		case "--name", "--module":
			if i+1 >= len(args) {
				return nil, nil, fmt.Errorf("%s requires a value", arg)
			}
			flags = append(flags, arg, args[i+1])
			i++
		case "--force":
			flags = append(flags, arg)
		default:
			if strings.HasPrefix(arg, "-") {
				return nil, nil, fmt.Errorf("unknown init flag %q", arg)
			}
			positionals = append(positionals, arg)
		}
	}
	return flags, positionals, nil
}

func runCheck(args []string, stdout io.Writer) error {
	target := "."
	if len(args) > 0 && !strings.HasPrefix(args[0], "-") {
		target = args[0]
	}
	absTarget, err := filepath.Abs(target)
	if err != nil {
		return fmt.Errorf("resolve target: %w", err)
	}
	required := []string{"go.mod", "main.go", "docs/router.go", "docs/icon.go", "content/index.md", "content/getting-started.md", "openapi.json", "public/favicon.svg", "agents/claude.md", ".agents/skills/docs-authoring/SKILL.md"}
	var missing []string
	for _, name := range required {
		if _, err := os.Stat(filepath.Join(absTarget, filepath.FromSlash(name))); err != nil {
			missing = append(missing, name)
		}
	}
	if len(missing) > 0 {
		return fmt.Errorf("project check failed; missing: %s", strings.Join(missing, ", "))
	}
	mainSource, err := os.ReadFile(filepath.Join(absTarget, "main.go"))
	if err != nil {
		return fmt.Errorf("read main.go: %w", err)
	}
	for _, marker := range []string{"buildSite", "MountNavigation", "MountCommandPalette", "WithPWA", "WithAppIcon", "WithSitemap", "WithRobots", "WithAgentReady", "MountAssets", "__fastr-docs/search.json"} {
		if !strings.Contains(string(mainSource), marker) {
			return fmt.Errorf("project check failed; main.go does not contain %q", marker)
		}
	}
	routerSource, err := os.ReadFile(filepath.Join(absTarget, "docs", "router.go"))
	if err != nil {
		return fmt.Errorf("read docs/router.go: %w", err)
	}
	source := string(routerSource)
	for _, marker := range []string{"NewRouter", "MustPage", "getting-started", "openapi.Plugin"} {
		if !strings.Contains(source, marker) {
			return fmt.Errorf("project check failed; docs/router.go does not contain %q", marker)
		}
	}
	_, _ = fmt.Fprintf(stdout, "project check passed: %s\n", absTarget)
	return nil
}

func runGo(args []string, command string, extra []string, stdout, stderr io.Writer) error {
	// The first argument may be a project directory. The remainder is passed to
	// Go unchanged, so the CLI remains a thin, predictable wrapper.
	var target string
	if len(args) > 0 && !strings.HasPrefix(args[0], "-") {
		target = args[0]
		args = args[1:]
	}
	if target == "" {
		target = "."
	}
	cmdArgs := append([]string{command}, extra...)
	cmdArgs = append(cmdArgs, args...)
	cmd := exec.Command("go", cmdArgs...)
	cmd.Dir = target
	cmd.Stdout = stdout
	cmd.Stderr = stderr
	return cmd.Run()
}

func runExport(args []string, stdout, stderr io.Writer) error {
	target := "."
	out := "dist"
	base := ""
	pagefind := false
	var positionals []string
	for i := 0; i < len(args); i++ {
		switch args[i] {
		case "--out", "--output":
			if i+1 >= len(args) {
				return fmt.Errorf("%s requires a value", args[i])
			}
			out = args[i+1]
			i++
		case "--base", "--export-base":
			if i+1 >= len(args) {
				return fmt.Errorf("%s requires a value", args[i])
			}
			base = args[i+1]
			i++
		case "--pagefind":
			pagefind = true
		default:
			if strings.HasPrefix(args[i], "-") {
				return fmt.Errorf("unknown export flag %q", args[i])
			}
			positionals = append(positionals, args[i])
		}
	}
	if len(positionals) > 0 {
		target = positionals[0]
	}
	goArgs := []string{"run", ".", "--export", out}
	if base != "" {
		goArgs = append(goArgs, "--export-base", base)
	}
	cmd := exec.Command("go", goArgs...)
	cmd.Dir = target
	if pagefind {
		cmd.Env = append(os.Environ(), "DOCS_SEARCH_BACKEND=pagefind")
	}
	cmd.Stdout = stdout
	cmd.Stderr = stderr
	if err := cmd.Run(); err != nil {
		return err
	}
	if !pagefind {
		return nil
	}
	return runPagefind(target, out, stdout, stderr)
}

func runPagefind(target, site string, stdout, stderr io.Writer) error {
	pagefindBin := strings.TrimSpace(os.Getenv("PAGEFIND_BIN"))
	if pagefindBin == "" {
		if _, err := exec.LookPath("pagefind"); err == nil {
			pagefindBin = "pagefind"
		} else if _, err := exec.LookPath("npx"); err == nil {
			pagefindBin = "npx"
		}
	}
	if pagefindBin == "" {
		return errors.New("fastr-docs: --pagefind requires the Pagefind CLI (install pagefind or set PAGEFIND_BIN)")
	}
	args := []string{"--site", site}
	if filepath.Base(pagefindBin) == "npx" || filepath.Base(pagefindBin) == "npx.cmd" {
		args = append([]string{"--no-install", "pagefind"}, args...)
	}
	cmd := exec.Command(pagefindBin, args...)
	cmd.Dir = target
	cmd.Stdout = stdout
	cmd.Stderr = stderr
	return cmd.Run()
}

type templateData struct {
	SiteName     string
	Module       string
	LocalReplace string
}

// localFastrDocsReplace makes projects generated from this checkout runnable
// before the module has been published. Installed binaries do not resolve to
// an existing source checkout, so released users keep the normal dependency
// graph from go.mod.tmpl.
func localFastrDocsReplace(target string) string {
	_, sourceFile, _, ok := runtime.Caller(0)
	if !ok {
		return ""
	}
	root := filepath.Clean(filepath.Join(filepath.Dir(sourceFile), "..", ".."))
	moduleSource, err := os.ReadFile(filepath.Join(root, "go.mod"))
	if err != nil || !strings.Contains(string(moduleSource), "module github.com/DonaldMurillo/fastr-docs") {
		return ""
	}
	relative, err := filepath.Rel(target, root)
	if err != nil || relative == "" {
		return ""
	}
	return filepath.ToSlash(relative)
}

func writeStarter(target string, data templateData, force bool) error {
	if err := os.MkdirAll(target, 0o755); err != nil {
		return fmt.Errorf("create target: %w", err)
	}
	return fs.WalkDir(starterTemplates, "templates/starter", func(path string, entry fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if entry.IsDir() {
			return nil
		}
		rel := strings.TrimPrefix(path, "templates/starter/")
		rel = strings.TrimSuffix(rel, ".tmpl")
		destination := filepath.Join(target, filepath.FromSlash(rel))
		if _, err := os.Stat(destination); err == nil && !force {
			return fmt.Errorf("refusing to overwrite %s; use --force", destination)
		}
		if err := os.MkdirAll(filepath.Dir(destination), 0o755); err != nil {
			return fmt.Errorf("create %s: %w", filepath.Dir(destination), err)
		}
		body, err := starterTemplates.ReadFile(path)
		if err != nil {
			return fmt.Errorf("read template %s: %w", path, err)
		}
		if strings.HasSuffix(path, ".tmpl") {
			tmpl, err := template.New(filepath.Base(path)).Funcs(template.FuncMap{
				"goString":   strconv.Quote,
				"jsonEscape": jsonEscape,
			}).Parse(string(body))
			if err != nil {
				return fmt.Errorf("parse template %s: %w", path, err)
			}
			var rendered strings.Builder
			if err := tmpl.Execute(&rendered, data); err != nil {
				return fmt.Errorf("render template %s: %w", path, err)
			}
			body = []byte(rendered.String())
		}
		if err := os.WriteFile(destination, body, 0o644); err != nil {
			return fmt.Errorf("write %s: %w", destination, err)
		}
		return nil
	})
}

func jsonEscape(value string) string {
	encoded, err := json.Marshal(value)
	if err != nil {
		panic(err)
	}
	return strings.TrimSuffix(strings.TrimPrefix(string(encoded), `"`), `"`)
}

func validModulePath(module string) bool {
	return !strings.ContainsAny(module, "\"'\\\r\n\t ") &&
		!strings.HasPrefix(module, "/") &&
		!strings.HasSuffix(module, "/") &&
		!strings.Contains(module, "//")
}

func printUsage(w io.Writer) {
	_, _ = fmt.Fprintln(w, "fastr-docs — create and run reusable documentation sites")
	_, _ = fmt.Fprintln(w, "")
	_, _ = fmt.Fprintln(w, "commands:")
	_, _ = fmt.Fprintln(w, "  init [dir]   create a strict, white-label starter project")
	_, _ = fmt.Fprintln(w, "  check [dir]  validate generated project conventions")
	_, _ = fmt.Fprintln(w, "  validate     alias for check")
	_, _ = fmt.Fprintln(w, "  doctor [dir] run conventions and the full Go test suite")
	_, _ = fmt.Fprintln(w, "  dev [dir]    run the GoFastr development server")
	_, _ = fmt.Fprintln(w, "  build [dir]  build the project and its packages")
	_, _ = fmt.Fprintln(w, "  export [dir] export a static PWA to dist (use --out or --pagefind to change it)")
}

func humanize(name string) string {
	name = strings.ReplaceAll(strings.ReplaceAll(name, "-", " "), "_", " ")
	if name == "" {
		return "Documentation"
	}
	return strings.ToUpper(name[:1]) + name[1:] + " Docs"
}
